### ISSUE TITLE
Next activity is in the past

### ISSUE THREAD

**Issue by YouKnowBlom** [Sermuns/undervisningsnummer#1]
When an activity has passed, then for the rest of the day it will say the next activity is the aforementioned activity. It should instead point to the next occurrence. For example, say there's an activity at 13:15. When the time passes 13:15 it will still say the next activity is on the same day at 13:15 despite it being in the past. This behavior only occurs on the same day as the activity and will work as intended again once the time passes midnight.

P.S. Thank you for making this useful tool 🥰

**Comment by Sermuns** [comment]
Could you check if this is still a problem? I was aware of this problem with my previous approach, but with some of the recent commits I reworked how the next occurences were calculated.

If you still find the problem, could you give me a screenshot?

P.S. Thank you for contributing to this project!
I recently added the feature to develop on this locally, so it should now be possible for you and others to contribute code to be ran on the backend Lysator server later!

**Comment by YouKnowBlom** [comment]
It works perfectly now, thank you!
